FROM node:21-bullseye

WORKDIR /gautam_saurav_ui_garden_build_checks

COPY package*.json ./

RUN npm ci

RUN npx playwright install --with-deps chromium

COPY . .

RUN npm install @storybook/cli --save-dev

CMD ["npm","run","ci:test"]
