name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

      - name: Build Storybook
        run: npm run build-storybook

      - name: Run Storybook interaction tests
        run: npx storybook test
